---
- name: Configuring tomcat9
  hosts: all
  tasks: 
   - name: Installing tomcat9
     apt: 
      name: tomcat9
      state: present
      update_cache: yes
   - name: Copy the tomcat9 file into servers
     copy: 
      src: /home/ubuntu/tomcat-users.xml
      dest: /etc/tomcat9
   - name: Changing the port number from 8080 to 8283
     replace: 
      regexp: 9090
      replace: 8283
      path: /etc/tomcat9/server.xml
   - name: Restart tomcat9
     service: 
      name: tomcat9
      state: restarted
   - name: pause for 30 seconds
     pause: 
      seconds: 30
   - name: url response of server1
     uri: 
      url: http://172.31.32.18
      status_code: 200
   - name: url response of server2
     uri: 
      url: http://172.31.36.94
      status_code: 200
...
